Allow More Retries and Add 1 Minute Retry Delay
ncipollo/release-action pull request #200
Opened 2022-04-16 11:09 UTC by justdan96

For a while we had been struggling with uploads to release artefacts, I switched us from a deprecated action to this one in an attempt to avoid ECONNRESET errors. Unfortunately we still saw these errors:
https://github.com/justdan96/tsMuxer/actions/runs/2080693953

My pull request allows 50 retries, rather than just 3, and also adds a 1 minute delay between retries. This seems to have fixed things for us but if a smart system which added a bit more time between retries depending on how many retries we have had could also be implemented I believe that would also work.

2022-04-19 14:57 UTC, ncipollo commented on src/ArtifactUploader.ts
> +                                 retry = 50) {
I don't know that we'd want to default this to 50 for everyone, this could lead to some really long delays if there is a legit failure.

2022-04-19 15:01 UTC, ncipollo requested changes
I don't think this behavior is something which would be generally useful for all users of the action. Having 50 retries with a fairly significant delay in between may have solved your case but that would potentially disrupt other users workflows (since it adds a huge delay if there are legit errors). 

I also don't know that this is a general solution to the issue since it's really a dice roll if github is going to succeed without failing when uploading these huge artifacts. It's also possible that this would push the workflow past it's max runtime (or drain a bunch of minutes from someone's account).

2022-04-19 15:01 UTC, ncipollo commented on src/ArtifactUploader.ts
> +                await new Promise(r => setTimeout(r, 60000));
Similarly, I don't think we'd want to add this delay for everyone. Minimally it would need to be configurable.

2022-04-19 15:01 UTC, ncipollo commented on src/ArtifactUploader.ts
> +                                 retry = 50) {
I don't know that we'd want to default this to 50 for everyone, this could lead to some really long delays if there is a legit failure.

2022-04-19 22:38 UTC, justdan96 commented
Those comments seem fair, would adding the maximum number of retries and the retry delay as configurable options be okay?

2022-04-20 01:58 UTC, ncipollo commented
> Those comments seem fair, would adding the maximum number of retries and the retry delay as configurable options be okay?

Yeah, I don't see any harm in that, if we go this route could we also update tests? It would also be good if we could avoid the delay, are you sure that's absolutely needed? I get that we don't want to bombard github but it does add some slowdown to the action and might make the test cases a bit more complicated.

2022-11-11 18:47 UTC, ncipollo commented
Closing out since this hasn't seen any movement in awhile.

2022-11-11 18:47 UTC, closed without merging