Add option to ignore prerelease on update
ncipollo/release-action pull request #96
Opened 2021-07-28 02:24 UTC by jashandeep-sohi

Hi,

This adds a `omitPrereleaseDuringUpdate` option, that should allow you to preserve the prerelease state on updates.

2021-07-28 14:07 UTC, ncipollo commented
Could you elaborate a little bit on the use case? Is there a scenario where you would want to create the release with the pre-release flag set to true but omit it when you update the release?

2021-07-28 15:24 UTC, jashandeep-sohi commented
To me updating a release is completely orthogonal to its prerelease status. For example, I create a prerelease `v1.2-alpha` in one workflow and in another upload additional assets for that release. That shouldn't automatically mark the release as no longer being a prerelease.

2021-07-28 17:12 UTC, ncipollo commented
Ah okay, that makes sense! Thanks for the additional context!

2021-07-28 18:59 UTC, ncipollo requested changes
The new functionality look great! I had a few small nits but after those are addressed I think this will be good to merge!

2021-07-28 18:59 UTC, ncipollo commented on README.md
> +- **omitPrereleaseDuringUpdate**: Indicates if the prerelease flag should be omitted during updates. The prerelease flag will still be applied for newly created releases.
Could we move this up with the rest of the `omit**` inputs? This list is roughly alphabetical.

2021-07-28 18:59 UTC, ncipollo commented on action.yml
> +  omitPrereleaseDuringUpdate:
Same here, could we move this up with the reset of the `omit*` inputs.

2021-07-28 18:59 UTC, ncipollo commented on src/Inputs.ts
> +    }
Could we also update the `prerelease` getter to `createdPrerelease` so it's consistent with the other inputs that have `created` vs `updated` variations?

2021-08-01 19:41 UTC, ncipollo approved these changes
Looks great, thanks for making those changes!

2021-08-01 19:41 UTC, merged